name: secure_counter
description: Example App for Amazon Cognito Identity SDK for Dart
environment:
  sdk: '>=2.12.0 <3.0.0'
version: 1.0.0+1
publish_to: none
dependencies:
  flutter:
    sdk: flutter
  amazon_cognito_identity_dart_2: #^1.0.0
    path: ../
  cupertino_icons:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
